# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@name permtest
#'@title permtest
NULL

#'@name hypergeo
#'@title hypergeo
#'@description
#'calculates an approximation for the hypergeometric function for use in DEGage_pdf. Equivalent
#'to a 2F1 hypergeometric function calcuation with series expansion.
#'@param a Upper bound 1
#'@param b Upper bound 2
#'@param c lower bound
#'@param x primary complex argument
NULL

#'@name adjust_r_lower
#'@title adjust_r_lower
#'@description
#'If one r value is too large for a pvalue to be calculated, the r value is adjusted until a p-value is calculable.
#'Generally only necessary in cases of extreme differential expression, hypergeometric function will not converge otherwise
#'This function operates for lower tailed tests.
#'@param r1 r parameter for the first group
#'@param p1 p parameter for the first group
#'@param r2 r parameter for the second group
#'@param p2 p parameter for the second group
#'@param dn The observed number of difference between the two groups
NULL

permtest <- function(genecount, group, levels, nperms) {
    .Call(`_DEGage_permtest`, genecount, group, levels, nperms)
}

DEGage_mean <- function(r1, p1, r2, p2) {
    .Call(`_DEGage_DEGage_mean`, r1, p1, r2, p2)
}

DEGage_pdf <- function(r1, p1, r2, p2, dn) {
    .Call(`_DEGage_DEGage_pdf`, r1, p1, r2, p2, dn)
}

DEGage_cdf <- function(r1, p1, r2, p2, k, maxiter) {
    .Call(`_DEGage_DEGage_cdf`, r1, p1, r2, p2, k, maxiter)
}

cdf_facilitator <- function(df, maxiter) {
    .Call(`_DEGage_cdf_facilitator`, df, maxiter)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_DEGage_RcppExport_registerCCallable`)
})
